In [1]:
print("Hello, World!")

Hello, World!


In [2]:
import testingmod as tm

tm.definition()

Hello, world!


In [3]:
# from tableAI import SimplexTableau

# t = SimplexTableau([1 2 1 0 0 0;
#                     2 1 0 1 0 14;
#                     1 1 0 0 1 8;])
# print(t)

In [4]:
import gaussian_elimination as ge

eq1 = ge.equation_system([[2, -1, 1],  # lhs
                       [2, -1, 1],
                       [4, 1, 1]],
                       [0, 0, 2])   # rhs
# eq1.to_reduced_triangular()


============================ LOG =================================

|   (2),     -1,      1 |     0 |
|   (2),     -1,      1 |     0 |
|   (4),      1,      1 |     2 |

Row 2 -> Row 2 - 1.000 * Row 1
Row 3 -> Row 3 - 2.000 * Row 1
Row 2 <-> Row 3
Now in triangular form.

|   (2),     -1,      1 |     0 |
|   0.0,  (3.0),   -1.0 |   2.0 |
|   0.0,    0.0,    0.0 |   0.0 |

Row 2 -> Row 2 * 0.333
Row 1 -> Row 1 * 0.500
Row 1 -> Row 1 + -0.500 * Row 2
Now in reduced triangular.

| (1.0),    0.0,  0.333 | 0.333 |
|   0.0,  (1.0), -0.333 | 0.667 |
|   0.0,    0.0,    0.0 |   0.0 |



In [5]:
import sangi as sg

In [6]:
eq3 = ([[2, -1, 1, 1],
     [2, -1, 1, 2],
     [4, 1, 1, 3]])
print(eq3[1])

[2, -1, 1, 2]


In [7]:
the = "the"
the += " test"
print(the)

the test


In [8]:
table = ""
for i in range(4-1, -1, -1):
    table += str(i) + "\t"
print(table)

3	2	1	0	


In [9]:
import numpy as np

# Original 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Original matrix:")
print(matrix)

# Shift elements right by one position (axis=1 for columns)
shifted_matrix = np.roll(matrix, -1, axis=1)

# Replace the "rolled" over values in the first column with 0s
# After rolling right, the original last column elements move to the first column
# We want to replace these with zeros to simulate a non-cyclic shift
shifted_matrix[:, 2] = 0

print("\nShifted right by 1 (with zeros):")
print(shifted_matrix)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shifted right by 1 (with zeros):
[[2 3 0]
 [5 6 0]
 [8 9 0]]


In [10]:
x = [1, 2, 3, 4, 5]
x2 = x + [0]
print(x2)

[1, 2, 3, 4, 5, 0]


In [11]:
m = [[0, 0, 0, 0], [0, -2, -7, -3], [0, 0, 0, 8], [0, 0, 0, 1]]
shifted_m = []
i = 1
for i in range(len(m)):
    shifted_m.append(np.roll(m[i], -i+1))
    print(shifted_m[i])
# shifted_m = np.roll(m, -1, axis=1)
# print("\nShifted m right by 1 (with zeros):")
# print(shifted_m)

[0 0 0 0]
[ 0 -2 -7 -3]
[0 0 8 0]
[0 1 0 0]


In [12]:
from sympy import symbols, sturm, count_roots

# Define variable and polynomial
x = symbols('x')
#p = x**2 + 8*x - 273 # Example polynomial
p = x**3 + 18*x**2 - 135*x - 2700

# 1. Compute the Sturm sequence
# Returns [p0, p1, ..., pn] where p0=p, p1=p'
seq = sturm(p, x)
print("Sturm Sequence:", seq)

# 2. Count distinct real roots in an interval, e.g., (-10, 10)
num_roots = count_roots(p, -30, 30)
print("Number of real roots in (-30, 30):", num_roots)

Sturm Sequence: [x**2 + 3*x - 180, 2*x + 3, 729/4]
Number of real roots in (-30, 30): 2


In [13]:
from sympy import symbols, solve

x = symbols('x')
expression = 100*x**3 -131*x**2 +755*x -625

# Find roots: [-2, 3]
my_roots_list = solve(expression, x) 
print(my_roots_list)

[131/300 + (-1/2 - sqrt(3)*I/2)*(42115841/27000000 + sqrt(240275857)/4000)**(1/3) - 209339/(90000*(-1/2 - sqrt(3)*I/2)*(42115841/27000000 + sqrt(240275857)/4000)**(1/3)), 131/300 - 209339/(90000*(-1/2 + sqrt(3)*I/2)*(42115841/27000000 + sqrt(240275857)/4000)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(42115841/27000000 + sqrt(240275857)/4000)**(1/3), -209339/(90000*(42115841/27000000 + sqrt(240275857)/4000)**(1/3)) + 131/300 + (42115841/27000000 + sqrt(240275857)/4000)**(1/3)]

In [14]:
# 1 -131 755 -625
# 1 -18 45
eq4 = sg.equation_system()

---------------------------------------------------------------------------------------------------------------------------------------------------------- 
Welcome to the Sangi Root Finder! 
This program will help you find integer roots of polynomials using a method similar to synthetic division. Let's get started! 
----------------------------------------------------------------------------------------------------------------------------------------------------------
Enter the coefficients of the equation, starting with the highest degree, separated by spaces. Use a dash before a number to indicate it is negative.
Coefficients entered: [1, -18, 45]
What range would you like to search for roots in? Enter the lower and upper bounds separated by a space.
Polynomial: 1*x**2 + -18*x**1 + 45*x**0
There are 2 roots in the interval [0, 30]
Would you like to try a new range? (Y/N)
Proceed with provided polynomial and range? (Y/N)
['000', '045', '0-1-8', '001']
[[0, 0, 0], [0, 4, 5], [0, -1, -8